apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
        localtime false
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
 
    <match kubernetes.**>
       @type elasticsearch
       @log_level info
       host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
       port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
       scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
       logstash_format true
       <buffer>
           @type file
           path /var/log/fluent/container.*.buffer
           chunk_limit_size 8MB
           total_limit_size 256MB
           chunk_full_threshold 0.95
           flush_mode interval
           flush_interval 10s
           overflow_action drop_oldest_chunk
           retry_timeout 24h
       </buffer>
       suppress_type_name true
    </match>
