apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/gateway-svc-*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag "#{ENV['FLUENT_CONTAINER_TAIL_TAG'] || 'kubernetes.*'}"
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>
  
    <match kubernetes.**>
       @type elasticsearch_dynamic
       host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
       port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
       logstash_format true
       logstash_prefix ${record['kubernetes']['namespace_name']}
       <buffer>
           @type file
           path /var/log/fluent/container.*.buffer
       </buffer>
    </match>
